// Роли авторов по-русски. Основа — раздел «РОЛИ ПЕРСОНАЛА В ПРОИЗВОДСТВЕ»
// из dictionary.json старого переводчика сайта (ветка main), отсюда же
// выкинуты метки-заголовки и пять строк релевантности тегов: ролями они не
// бывают. Сверх него два слова из 3.0: «Music» и «Theme Song Arrangement».
// Незнакомая роль показывается как пришла: прятать её хуже, чем не перевести.
export const CREW_WORDS: Record<string, string> = {
  // Верхушка тайтла
  Director: 'Режиссёр',
  'Chief Director': 'Главный режиссёр',
  'Assistant Director': 'Помощник режиссёра',
  'Unit Director': 'Постановщик',
  'Chief Unit Director': 'Главный постановщик',
  'Assistant Unit Director': 'Помощник постановщика',
  'Episode Director': 'Режиссёр эпизода',
  'Assistant Episode Director': 'Помощник режиссёра эпизода',
  'Chief Supervisor': 'Главный супервайзер',
  Supervisor: 'Супервайзер',
  Supervision: 'Контроль',

  // Первоисточник и сценарий
  'Original Creator': 'Автор оригинала',
  'Original Story': 'Оригинальный сюжет',
  Story: 'Сюжет',
  'Story & Art': 'Сюжет и рисовка',
  Art: 'Рисовка',
  Illustration: 'Иллюстрации',
  Script: 'Сценарий',
  'Script Assistance': 'Помощь в написании сценария',
  'Special Production Team Script': 'Сценарий спецкоманды',
  'Series Composition': 'Композиция серий',
  Storyboard: 'Раскадровка',
  'Storyboard Draft': 'Черновик раскадровки',
  'Recollection Part Storyboard': 'Раскадровка сцен воспоминаний',
  'Image Board': 'Имидж-борд',
  'Idea Assistance': 'Помощь в идее',

  // Дизайн
  'Character Design': 'Дизайн персонажей',
  'Original Character Design': 'Оригинальный дизайн персонажей',
  'Main Character Design': 'Дизайн главных персонажей',
  'Sub Character Design': 'Дизайн второстепенных персонажей',
  'Mechanical Design': 'Дизайн мехов',
  'Main Mechanical Design': 'Основной дизайн мехов',
  'Prop Design': 'Дизайн реквизита',
  'Art Design': 'Художественный дизайн',
  'Concept Design': 'Концепт-дизайн',
  Design: 'Дизайн',
  'Design Works': 'Разработка дизайна',
  'Detail Works': 'Проработка деталей',
  'Design Manager': 'Менеджер по дизайну',
  'Production Design': 'Производственный дизайн',
  Layout: 'Лейаут',
  'Layout Design': 'Дизайн лейаутов',
  'Layout Assistance': 'Помощь в создании лейаутов',
  'Title Design': 'Дизайн логотипа',
  'Title Logo Design': 'Дизайн логотипа',
  'Main Title Logo Design': 'Дизайн логотипа',
  'Advertising Design': 'Рекламный дизайн',
  'Technical Design': 'Технический дизайн',

  // Анимация
  'Animation Director': 'Режиссёр анимации',
  'Chief Animation Director': 'Главный режиссёр анимации',
  'Assistant Animation Director': 'Помощник режиссёра анимации',
  Animation: 'Анимация',
  'Key Animation': 'Ключевая анимация',
  '2nd Key Animation': 'Вторая ключевая анимация',
  'In-Between Animation': 'Промежуточная анимация',
  'In-Betweens Check': 'Проверка фазовки',
  'In-Betweens Check Assistance': 'Помощь в проверке фазовки',
  'Animation Producer': 'Продюсер анимации',

  // Фоны, цвет и покраска
  'Art Director': 'Художник-постановщик',
  'Background Art': 'Художник фонов',
  'Matte Painting': 'Мэтт-пейнтинг',
  'Color Design': 'Цветовой дизайн',
  'Color Coordination': 'Координация цвета',
  'Color Specification': 'Спецификация цвета',
  'Color Manager': 'Менеджер по цвету',
  Finishing: 'Финишная обработка',
  'Finishing Check': 'Проверка финишной обработки',
  'Finishing Check Assistance': 'Помощь в проверке финишной обработки',
  'Finishing Manager': 'Менеджер финишной обработки',
  'Digital Paint': 'Цифровая покраска',
  Paint: 'Покраска',

  // Съёмка и эффекты
  'Director of Photography': 'Оператор-постановщик',
  'Assistant Director of Photography': 'Помощник оператора-постановщика',
  'Digital Photography': 'Цифровая съёмка',
  'Photography Assistance': 'Помощь в съёмке',
  'Special Effects': 'Спецэффекты',
  'Special Effects Director': 'Режиссёр спецэффектов',
  'Special Effects Supervisor': 'Супервайзер спецэффектов',
  'Special Effects Assistance': 'Помощь со спецэффектами',
  'Special Synthetic Artist': 'Художник по спецэффектам',
  'Visual Effects Artist': 'Художник визуальных эффектов',
  'Flashback Scene Director': 'Режиссёр сцен воспоминаний',
  'Flashback Scene Key Animation': 'Ключевая анимация сцен воспоминаний',
  'Flashback Scene Photography': 'Съёмка сцен воспоминаний',

  // CG
  'CG Director': 'CG-режиссёр',
  'CG Animation': 'CG-анимация',
  'CG Producer': 'CG-продюсер',
  'CG Director of Photography': 'Оператор-постановщик CG',
  'CG Unit Director': 'CG-постановщик',
  'CG Design': 'CG-дизайн',
  'CG Operator': 'CG-оператор',
  'CG Assistance': 'Помощь в CG',
  'CG Production Assistant': 'Ассистент производства CG',
  'CG Production Assistance': 'Помощь в производстве CG',
  'CG production Assistance': 'Помощь в производстве CG',
  '3DCG Background Art': '3DCG-фоны',
  'Digital Director': 'Диджитал-режиссёр',
  'Digital Unit Director': 'Цифровой постановщик',
  '2D Works': '2D-графика',
  '2D Digital Works': '2D-цифровая графика',
  '2D Digital Work Assistance': 'Помощь в 2D-цифровой обработке',
  'Monitor Works': 'Оформление мониторов',
  'Monitor Design Assistance': 'Помощь в дизайне мониторов',
  Telop: 'Телоп',

  // Звук и музыка
  'Sound Director': 'Звукорежиссёр',
  'Sound Effects': 'Звуковые эффекты',
  'Sound Engineer': 'Звукоинженер',
  'Sound Adjustment': 'Корректировка звука',
  'Sound Adjustment Assistance': 'Помощь в настройке звука',
  'Sound Production': 'Звуковое производство',
  'Sound Production Manager': 'Менеджер по производству звука',
  Recording: 'Запись',
  'Recording Assistant': 'Ассистент записи',
  'Recording Adjustment': 'Корректировка записи',
  'Recording Studio': 'Студия записи',
  'Recording Studio Staff': 'Персонал студии записи',
  'Optical Recording': 'Оптическая запись',
  'Optical Re-Recording': 'Оптическая перезапись',
  'Digital Optical Recording': 'Цифровая оптическая запись',
  Mixing: 'Сведение',
  'ADR Director': 'Режиссёр дубляжа',
  'ADR Engineer': 'Звукоинженер дубляжа',
  'ADR Mixing Engineer': 'Инженер сведения дубляжа',
  'ADR Recording Engineer': 'Инженер записи дубляжа',
  'ADR Editor': 'Монтажёр дубляжа',
  'ADR Sound Mixing': 'Сведение звука дубляжа',
  'ADR Translator': 'Переводчик дубляжа',
  'Casting Manager': 'Кастинг-менеджер',
  Music: 'Музыка',
  'Music Composition': 'Композиция музыки',
  'Music Lyrics': 'Текст песни',
  'Music Performance': 'Исполнение музыки',
  'Music Producer': 'Музыкальный продюсер',
  'Music Director': 'Музыкальный руководитель',
  'Music Production': 'Музыкальное производство',
  'Music Production Manager': 'Менеджер музыкального производства',
  'Theme Song Performance': 'Исполнение заглавной песни',
  'Theme Song Composition': 'Композиция заглавной песни',
  'Theme Song Lyrics': 'Текст заглавной песни',
  'Theme Song Arrangement': 'Аранжировка темы',
  'Theme Song Performance (OP)': 'Исполнение песни (OP)',
  'Theme Song Performance (ED)': 'Исполнение песни (ED)',
  'Theme Song Composition (OP)': 'Композиция песни (OP)',
  'Theme Song Composition (ED)': 'Композиция песни (ED)',
  'Theme Song Lyrics (OP)': 'Текст песни (OP)',
  'Theme Song Lyrics (ED)': 'Текст песни (ED)',
  'Theme Song Arrangement (OP)': 'Аранжировка песни (OP)',
  'Theme Song Arrangement (ED)': 'Аранжировка песни (ED)',
  'Main Theme': 'Основная тема',
  'Insert Song Performance': 'Исполнение вставной песни',
  'Insert Song Composition': 'Композиция вставной песни',
  'Insert Song Lyrics': 'Текст вставной песни',
  'Insert Song Arrangement': 'Аранжировка вставной песни',
  'Choreography (OP)': 'Хореография (OP)',
  'Choreography (ED)': 'Хореография (ED)',

  // Монтаж
  Editing: 'Монтаж',
  'Editing Assistant': 'Ассистент монтажа',
  'Finishing Editing': 'Финальный монтаж',
  'Online Editing': 'Онлайн-монтаж',
  Timing: 'Тайминг',

  // Производство и прочее
  Producer: 'Продюсер',
  Producers: 'Продюсеры',
  'Executive Producer': 'Исполнительный продюсер',
  'Associate Producer': 'Ассоциированный продюсер',
  'Assistant Producer': 'Помощник продюсера',
  Production: 'Производство',
  'Production Assistance': 'Помощь в производстве',
  'Production Assistant': 'Ассистент производства',
  'Assistant Production Manager': 'Помощник менеджера производства',
  'Production Desk': 'Производственный координатор',
  'Production Generalization': 'Общее руководство производством',
  'Production Committee': 'Производственный комитет',
  'Planning Assistance': 'Помощь в планировании',
  'Planning Manager': 'Менеджер по планированию',
  Advertising: 'Реклама',
  'Advertising Assistance': 'Помощь в рекламе',
  'Copyright Manager': 'Менеджер по авторским правам',
  'Studio Manager': 'Менеджер студии',
  'Lab Manager': 'Менеджер лаборатории',
  Editor: 'Редактор',
  Translator: 'Переводчик',
  Lettering: 'Леттеринг',
  'Poster Art': 'Арт для постеров',
  'Poster Illustration': 'Иллюстрация постера',
  'Insert Drawing': 'Вставные рисунки',
  'Special Thanks': 'Особая благодарность',
}
